# Autograd : Derivative calculation tool

In [1]:
import torch

#### Define a tensor with `requires_grad=True`

In [20]:
x = torch.tensor(3.0, requires_grad=True)

In [21]:
y = x**2

In [22]:
print(x)
print(y)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)


#### CAlculate derivative of dy/dx

In [12]:
# Calculates all the derivatives in backward.
y.backward()

In [14]:
# value of dy/dx
x.grad

tensor(6.)

In [23]:
z = torch.sin(y)

In [24]:
print(x)
print(y)
print(z)

tensor(3., requires_grad=True)
tensor(9., grad_fn=<PowBackward0>)
tensor(0.4121, grad_fn=<SinBackward0>)


In [25]:
z.backward(retain_graph=True)

In [26]:
print(y.grad)
print(x.grad)

None
tensor(-5.4668)


/tmp/ipykernel_545/2314068748.py:1: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the .grad field to be populated for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations. (Triggered internally at /opt/conda/conda-bld/pytorch_1729647327489/work/build/aten/src/ATen/core/TensorBody.h:489.)
  print(y.grad)


### NN using autograd

In [27]:
x = torch.tensor(6.79)
y = torch.tensor(0)

In [28]:
w = torch.tensor(1.0, requires_grad=True)
b = torch.tensor(0.0, requires_grad=True)

In [32]:
# loss function
def binary_cross_entropy_loss(y_pred, y):
    return -(y*torch.log(y_pred)+(1-y)*torch.log(1-y_pred))

In [29]:
# Forward Pass
z = w*x + b
z

tensor(6.7900, grad_fn=<AddBackward0>)

In [30]:
y_pred = torch.sigmoid(z)
y_pred

tensor(0.9989, grad_fn=<SigmoidBackward0>)

In [33]:
loss = binary_cross_entropy_loss(y_pred, y)
loss

tensor(6.7911, grad_fn=<NegBackward0>)

In [34]:
loss.backward()

In [35]:
print(w.grad)
print(b.grad)

tensor(6.7824)
tensor(0.9989)


### For vector

In [37]:
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
x

tensor([1., 2., 3.], requires_grad=True)

In [39]:
y = (x**2).mean()
y

tensor(4.6667, grad_fn=<MeanBackward0>)

In [40]:
y.backward()

In [41]:
x.grad

tensor([0.6667, 1.3333, 2.0000])

### Clearing grad

In [51]:
x = torch.tensor(3.0, requires_grad=True)

In [73]:
y = x ** 2

In [74]:
y.backward()

In [75]:
# by running it 2 times it sum the grad from previous value
x.grad

tensor(12.)

In [69]:
x.grad.zero_()

tensor(0.)

Run above codes for more intuition

### Disable gradient tracking

In [42]:
x = torch.tensor(3.0, requires_grad=True)
y = x ** 2

In [43]:
y.backward()

In [44]:
x.grad

tensor(6.)

In [45]:
# option 1
x.requires_grad_(False)

tensor(3.)

In [48]:
# option 2: Detach
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)
print("x:", x)

z = x.detach()
print("z:", z)

x: tensor([1., 2., 3.], requires_grad=True)
z: tensor([1., 2., 3.])


In [50]:
# option 3: no_grad() 
x = torch.tensor([1.0, 2.0, 3.0], requires_grad=True)

y = x ** 2 
print(y)

with torch.no_grad():
    y = x ** 2
    print(y)

tensor([1., 4., 9.], grad_fn=<PowBackward0>)
tensor([1., 4., 9.])
