# Pytorch nn module

In [1]:
# import
import torch
import torch.nn as nn

In [10]:
# create nn model
class Model(nn.Module):

    def __init__(self, num_features):
        # call super class (nn class) constructor.
        super().__init__()
        # create a single neuron.
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid = nn.Sigmoid()

    def forward(self, features):

        out = self.linear(features)
        out = self.sigmoid(out)

        return out

In [6]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.5918],
        [0.5448],
        [0.5717],
        [0.6547],
        [0.6257],
        [0.4926],
        [0.5170],
        [0.5369],
        [0.6145],
        [0.5827]], grad_fn=<SigmoidBackward0>)

In [7]:
# model weights & bias

print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[-0.0425,  0.3076,  0.2490, -0.4051, -0.2240]], requires_grad=True)
Parameter containing:
tensor([0.4150], requires_grad=True)


In [8]:
!pip install torchinfo

In [9]:
from torchinfo import summary

summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (M): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Neural Network : 1 hidden layer of 3 neurons & 1 O/P layer of 1 neuron

In [19]:
# create nn model
class Model(nn.Module):

    # def __init__(self, num_features):
    #     # call super class (nn class) constructor.
    #     super().__init__()
    #     # create hidden layer with output of 3.
    #     self.linear1 = nn.Linear(num_features, 3)
    #     self.relu = nn.ReLU()
    #     # create output layer of 1 neuron with 1 o/p.
    #     self.linear2 = nn.Linear(3, 1)
    #     self.sigmoid = nn.Sigmoid()

    # def forward(self, features):
    #     # layer 1
    #     out = self.linear1(features)
    #     out = self.relu(out)
    #     # layer 2
    #     out = self.linear2(out)
    #     out = self.sigmoid(out)

    # sequential 
    def __init__(self, num_features):
        # call super class (nn class) constructor.
        super().__init__()

        self.network = nn.Sequential(
        
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3, 1),
        nn.Sigmoid(),
        )

    def forward(self, features):
        out = self.network(features)
        return out

In [20]:
# create dataset
features = torch.rand(10, 5)

# create model
model = Model(features.shape[1])

# call model for forward pass
model(features)

tensor([[0.5155],
        [0.5090],
        [0.5240],
        [0.5001],
        [0.5001],
        [0.5001],
        [0.5271],
        [0.5001],
        [0.5001],
        [0.5260]], grad_fn=<SigmoidBackward0>)

In [18]:
# model weights & bias

print(model.linear1.weight)
print(model.linear1.bias)
print(model.linear2.weight)
print(model.linear2.bias)


Parameter containing:
tensor([[ 0.2599,  0.1335,  0.1326, -0.3455,  0.2519],
        [ 0.0351,  0.3467,  0.1212, -0.4402, -0.2869],
        [ 0.2860,  0.3852, -0.3624,  0.1211, -0.2676]], requires_grad=True)
Parameter containing:
tensor([ 0.0094,  0.1434, -0.2445], requires_grad=True)
Parameter containing:
tensor([[ 0.1735, -0.1544,  0.4339]], requires_grad=True)
Parameter containing:
tensor([-0.3340], requires_grad=True)
