# PyTroch : Tensors

In [1]:
import torch

In [5]:
print(torch.__version__)

2.5.1


In [6]:
print(torch.cuda.is_available())

True


In [7]:
print(torch.cuda.get_device_name(0))

NVIDIA GeForce RTX 3050 Laptop GPU


## Creating a Tensor

In [9]:
a = torch.empty(2,3)
type(a)

torch.Tensor

In [10]:
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [11]:
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [12]:
torch.rand(2,3)

tensor([[0.0382, 0.6280, 0.2742],
        [0.5899, 0.7565, 0.6166]])

In [21]:
# manual seed
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [22]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [24]:
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [25]:
torch.arange(0,10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [26]:
torch.arange(0,20,2)

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [31]:
torch.linspace(1,30,10) # 10 evenly space between each values

tensor([ 1.0000,  4.2222,  7.4444, 10.6667, 13.8889, 17.1111, 20.3333, 23.5556,
        26.7778, 30.0000])

In [33]:
# identity matrix
torch.eye(3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [35]:
x = torch.full((3,3), 5)
x

tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])

### Tensor Shape

In [36]:
x = torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [37]:
x.shape

torch.Size([2, 3])

#### Copy shape of a tensor

In [41]:
y = torch.empty_like(x)
y.shape

torch.Size([2, 3])

In [43]:
y = torch.zeros_like(x)
y

tensor([[0, 0, 0],
        [0, 0, 0]])

In [44]:
y = torch.ones_like(x)
y

tensor([[1, 1, 1],
        [1, 1, 1]])

In [55]:
y = torch.rand_like(x, dtype=torch.float64)
y

tensor([[0.7911, 0.4274, 0.4460],
        [0.5522, 0.9559, 0.9405]], dtype=torch.float64)

### Tensor Data Types

In [46]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.dtype

torch.int64

In [51]:
# assign a datatype
x = torch.tensor([[1.2,2.8,3],[4,5,6]], dtype=torch.int32)
print(x)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)


In [52]:
x = torch.tensor([[1,2,3],[4,5,6]], dtype=torch.float32)
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [53]:
# convert datatype
x.to(torch.int32)

tensor([[1, 2, 3],
        [4, 5, 6]], dtype=torch.int32)

### Mathematical Operations

In [57]:
x = torch.rand(3,3)

In [59]:
x

tensor([[0.8902, 0.5163, 0.0359],
        [0.6476, 0.3430, 0.3182],
        [0.5261, 0.0447, 0.5123]])

In [58]:
# Addition
x + 2

tensor([[2.8902, 2.5163, 2.0359],
        [2.6476, 2.3430, 2.3182],
        [2.5261, 2.0447, 2.5123]])

In [60]:
x - 3

tensor([[-2.1098, -2.4837, -2.9641],
        [-2.3524, -2.6570, -2.6818],
        [-2.4739, -2.9553, -2.4877]])

In [63]:
x = x * 100
x

tensor([[8901.9795, 5162.7129,  358.8456],
        [6476.3276, 3430.2563, 3182.4023],
        [5260.8770,  446.5872, 5123.4800]])

In [65]:
x = x / 10
x

tensor([[890.1979, 516.2713,  35.8846],
        [647.6328, 343.0256, 318.2402],
        [526.0877,  44.6587, 512.3480]])

In [66]:
x = x % 2
x

tensor([[0.1979, 0.2713, 1.8846],
        [1.6328, 1.0256, 0.2402],
        [0.0877, 0.6587, 0.3480]])

#### 2 Tensors

In [67]:
x = torch.ones(3,3)
y = torch.ones(3,3)

In [69]:
x + y

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [72]:
x = y+2

In [75]:
print(x)
print(y)

tensor([[5., 5., 5.],
        [5., 5., 5.],
        [5., 5., 5.]])
tensor([[3., 3., 3.],
        [3., 3., 3.],
        [3., 3., 3.]])


In [73]:
x ** y

tensor([[125., 125., 125.],
        [125., 125., 125.],
        [125., 125., 125.]])

#### Other operations

In [77]:
x = torch.tensor([1,2,-3,4,-5])

In [78]:
torch.abs(x)

tensor([1, 2, 3, 4, 5])

In [79]:
torch.neg(x)

tensor([-1, -2,  3, -4,  5])

In [81]:
x = torch.rand(3)
torch.round(x)

tensor([1., 1., 0.])

In [82]:
x = torch.tensor([3.5, 6.8, 1.3, 9.4])

In [83]:
torch.ceil(x)

tensor([ 4.,  7.,  2., 10.])

In [84]:
torch.floor(x)

tensor([3., 6., 1., 9.])

In [88]:
# clamp : all values should be converted in range btw min & max
torch.clamp(x, min=3, max=8)

tensor([3.5000, 6.8000, 3.0000, 8.0000])

## Reduction Operation

In [90]:
x = torch.randint(size=(3,3), low=0, high=10)
x

tensor([[5, 5, 0],
        [4, 3, 8],
        [8, 3, 3]])

In [91]:
x.sum()

tensor(39)

In [97]:
# column wise summation
print(x.sum(axis=0)) # also write (dim = 0)
print(torch.sum(x, dim=0))

tensor([17, 11, 11])
tensor([17, 11, 11])


In [95]:
# row wise
x.sum(dim=1)

tensor([10, 15, 14])

In [101]:
# mean
x = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float64)
print(x)
torch.mean(x)

tensor([[3., 8., 5.],
        [6., 2., 9.],
        [5., 0., 4.]], dtype=torch.float64)


tensor(4.6667, dtype=torch.float64)

In [102]:
# column
print(torch.mean(x, dim=0))
# row
print(torch.mean(x, dim=1))

tensor([4.6667, 3.3333, 6.0000], dtype=torch.float64)
tensor([5.3333, 5.6667, 3.0000], dtype=torch.float64)


In [103]:
# Median
torch.median(x)

tensor(5., dtype=torch.float64)

In [104]:
# max & min
print(torch.max(x))
print(torch.min(x))

tensor(9., dtype=torch.float64)
tensor(0., dtype=torch.float64)


## Matrix operation

In [111]:
a = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float64)
b = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float64)

In [112]:
print(a)
print(b)

tensor([[4., 6., 6.],
        [8., 4., 9.],
        [0., 7., 9.]], dtype=torch.float64)
tensor([[2., 7., 0.],
        [2., 4., 4.],
        [6., 2., 1.]], dtype=torch.float64)


In [115]:
# multiplication
m = torch.matmul(a, b)
m

tensor([[56., 64., 30.],
        [78., 90., 25.],
        [68., 46., 37.]], dtype=torch.float64)

In [120]:
# Dot Product
c = torch.tensor([3.5, 6.8, 1.3, 9.4])
d = torch.tensor([3.5, 6.8, 1.3, 9.4])
dot = torch.dot(c, d)
dot

tensor(148.5400)

In [126]:
# transpose
print("Before:", a)
a = torch.transpose(a, 0, 1)
print(a)

Before: tensor([[4., 6., 6.],
        [8., 4., 9.],
        [0., 7., 9.]], dtype=torch.float64)
tensor([[4., 8., 0.],
        [6., 4., 7.],
        [6., 9., 9.]], dtype=torch.float64)


## Special Functions

In [128]:
x = torch.randint(size=(3,3), low=1, high=10, dtype=torch.float64)
x

tensor([[8., 1., 6.],
        [4., 5., 4.],
        [9., 4., 7.]], dtype=torch.float64)

In [130]:
# log
x.log()
torch.log(x)

tensor([[2.0794, 0.0000, 1.7918],
        [1.3863, 1.6094, 1.3863],
        [2.1972, 1.3863, 1.9459]], dtype=torch.float64)

In [131]:
x.exp()

tensor([[2.9810e+03, 2.7183e+00, 4.0343e+02],
        [5.4598e+01, 1.4841e+02, 5.4598e+01],
        [8.1031e+03, 5.4598e+01, 1.0966e+03]], dtype=torch.float64)

In [132]:
x.sqrt()

tensor([[2.8284, 1.0000, 2.4495],
        [2.0000, 2.2361, 2.0000],
        [3.0000, 2.0000, 2.6458]], dtype=torch.float64)

In [133]:
x.sigmoid()

tensor([[0.9997, 0.7311, 0.9975],
        [0.9820, 0.9933, 0.9820],
        [0.9999, 0.9820, 0.9991]], dtype=torch.float64)

In [135]:
x.softmax(1)

tensor([[8.8009e-01, 8.0254e-04, 1.1911e-01],
        [2.1194e-01, 5.7612e-01, 2.1194e-01],
        [8.7560e-01, 5.8998e-03, 1.1850e-01]], dtype=torch.float64)

In [136]:
x.relu()

tensor([[8., 1., 6.],
        [4., 5., 4.],
        [9., 4., 7.]], dtype=torch.float64)

### Inplace Operation <br>
Writing `_` at the end of function makes it inplace operation

In [138]:
a = torch.rand(3,3)
b = torch.rand(3,3)

In [139]:
a, b

(tensor([[0.6818, 0.1953, 0.9991],
         [0.1133, 0.0135, 0.1450],
         [0.7819, 0.3134, 0.2983]]),
 tensor([[0.3436, 0.2028, 0.9792],
         [0.4947, 0.3617, 0.9687],
         [0.0359, 0.3041, 0.9867]]))

In [140]:
a.add_(b)

tensor([[1.0253, 0.3981, 1.9783],
        [0.6080, 0.3752, 1.1137],
        [0.8179, 0.6175, 1.2850]])

In [141]:
a

tensor([[1.0253, 0.3981, 1.9783],
        [0.6080, 0.3752, 1.1137],
        [0.8179, 0.6175, 1.2850]])

### Copying Tensor

In [142]:
a = torch.rand(3,3)
a

The history saving thread hit an unexpected error (OperationalError('attempt to write a readonly database')).History will not be written to the database.


tensor([[0.1290, 0.6887, 0.1637],
        [0.0899, 0.3139, 0.1219],
        [0.3516, 0.2316, 0.2847]])

In [143]:
a = b
b

tensor([[0.3436, 0.2028, 0.9792],
        [0.4947, 0.3617, 0.9687],
        [0.0359, 0.3041, 0.9867]])

In [144]:
b[0][0] = 99

In [146]:
a, b # in both the changes are reflected!!

(tensor([[9.9000e+01, 2.0277e-01, 9.7920e-01],
         [4.9468e-01, 3.6170e-01, 9.6867e-01],
         [3.5917e-02, 3.0412e-01, 9.8666e-01]]),
 tensor([[9.9000e+01, 2.0277e-01, 9.7920e-01],
         [4.9468e-01, 3.6170e-01, 9.6867e-01],
         [3.5917e-02, 3.0412e-01, 9.8666e-01]]))

In [147]:
# `a`& `b` are pointing to same memory location
print(id(a))
print(id(b))

139940246175664
139940246175664


In [148]:
# To avoid the same location use `clone()` function
b = a.clone()

In [149]:
b

tensor([[9.9000e+01, 2.0277e-01, 9.7920e-01],
        [4.9468e-01, 3.6170e-01, 9.6867e-01],
        [3.5917e-02, 3.0412e-01, 9.8666e-01]])

In [150]:
print(id(a))
print(id(b))

139940246175664
139940250425584


In [151]:
b = b + 100

In [152]:
a, b

(tensor([[9.9000e+01, 2.0277e-01, 9.7920e-01],
         [4.9468e-01, 3.6170e-01, 9.6867e-01],
         [3.5917e-02, 3.0412e-01, 9.8666e-01]]),
 tensor([[199.0000, 100.2028, 100.9792],
         [100.4947, 100.3617, 100.9687],
         [100.0359, 100.3041, 100.9867]]))

## Tensor Operation on GPU

In [153]:
torch.cuda.is_available()

True

In [155]:
device = torch.device('cuda')

In [156]:
x

tensor([[8., 1., 6.],
        [4., 5., 4.],
        [9., 4., 7.]], dtype=torch.float64)

In [158]:
y = torch.rand((3,3), device=device)
y

tensor([[0.8344, 0.7001, 0.5361],
        [0.8883, 0.0220, 0.7938],
        [0.7543, 0.6514, 0.9609]], device='cuda:0')

In [159]:
# Shift `x` to GPU 
x.to(device)

tensor([[8., 1., 6.],
        [4., 5., 4.],
        [9., 4., 7.]], device='cuda:0', dtype=torch.float64)

### Compare CPU & GPU

In [162]:
import time

size = 10000

matrix_cpu_1 = torch.randn(size, size)
matrix_cpu_2 = torch.randn(size, size)

start_time = time.time()
result_cpu = torch.matmul(matrix_cpu_1, matrix_cpu_2)
cpu_time = time.time() - start_time

print(f"CPU Time: {cpu_time}")

matrix_gpu_1 = matrix_cpu_1.to(device)
matrix_gpu_2 = matrix_cpu_2.to(device)

start_time = time.time()
result_cpu = torch.matmul(matrix_gpu_1, matrix_gpu_2)
gpu_time = time.time() - start_time

print(f"CPU Time: {gpu_time}")

CPU Time: 5.220487117767334
CPU Time: 0.0011539459228515625


### Reshpae Tensor

In [167]:
x = torch.randn(4, 4)
x

tensor([[-0.1555, -0.8466, -0.5231,  1.5325],
        [ 0.0759, -0.2288,  1.4980,  0.2568],
        [ 0.1835, -0.1755, -0.3987,  0.2313],
        [-0.7313, -0.1407,  0.5595,  1.0269]])

In [166]:
x.reshape(2,2,2,2)

tensor([[[[-1.4562, -0.3765],
          [-0.2657, -1.8280]],

         [[-0.7237, -0.6533],
          [ 1.0785,  0.9002]]],


        [[[-1.7041,  1.3252],
          [-0.4099, -0.7070]],

         [[ 1.3148, -0.3568],
          [-2.8220, -2.2065]]]])

In [168]:
x = torch.rand(2,3,4)

In [169]:
x.shape

torch.Size([2, 3, 4])

In [172]:
# permute : It interchanges the dimention 
y = x.permute(2,0,1)
y.shape

torch.Size([4, 2, 3])

In [177]:
# unsqueeze : add a dimention at specified index
y = x.unsqueeze(1)
y.shape

torch.Size([2, 1, 3, 4])

In [179]:
x

tensor([[[0.9738, 0.4766, 0.4465, 0.7665],
         [0.8807, 0.6201, 0.5850, 0.4287],
         [0.2153, 0.6954, 0.2543, 0.6952]],

        [[0.3801, 0.9545, 0.8934, 0.0958],
         [0.2108, 0.8729, 0.3142, 0.7949],
         [0.4441, 0.9079, 0.8278, 0.3379]]])

In [186]:
# squeeze
x.squeeze(0).shape

torch.Size([2, 3, 4])

In [189]:
a = torch.rand(1,20,2)
print(a.shape)
print(a.squeeze(0).shape)

torch.Size([1, 20, 2])
torch.Size([20, 2])
